#!/usr/bin/env bash
set -e

echo "? Vercel deploy: vilvi-site"
vercel deploy --prod --yes --scope vilvi-aa712e28 --cwd apps/site

echo "? Vercel deploy: vilvi-web"
vercel deploy --prod --yes --scope vilvi-aa712e28 --cwd apps/web

echo "? Vercel deploy: vilvi-unga"
vercel deploy --prod --yes --scope vilvi-aa712e28 --cwd apps/unga

echo "? Vercel deploy: vilvi-admin"
vercel deploy --prod --yes --scope vilvi-aa712e28 --cwd apps/admin

echo "? Alla deploys klara."
